# Generated by Django 5.1.6 on 2025-05-09 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_favoritos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favoritos',
            constraint=models.UniqueConstraint(fields=('usuario', 'produto'), name='unique_favorito'),
        ),
    ]
