# Generated by Django 5.1.6 on 2025-05-20 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_favoritos_unique_favorito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compra',
        ),
    ]
