# Generated by Django 5.1.6 on 2025-05-20 19:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_delete_compra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.IntegerField()),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('parcelas', models.IntegerField(default=1)),
                ('quantidade', models.IntegerField()),
                ('frete_id', models.IntegerField(default=0)),
                ('endereco', models.CharField(max_length=225)),
                ('tempo_previsto', models.IntegerField()),
                ('tempo_chegada', models.IntegerField()),
                ('valor_compra', models.FloatField()),
                ('status', models.IntegerField(default=1)),
                ('forma_pag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forma_pag', to='sistema.formapag')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
