# Generated by Django 5.1.6 on 2025-06-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='tempo_chegada',
            field=models.IntegerField(null=True),
        ),
    ]
